version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: redx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: redx_fe_test
      POSTGRES_USER: redx_user
      POSTGRES_PASSWORD: redx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redx_user -d redx_fe_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: redx-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://redx_user:redx_password@postgres:5432/redx_fe_test
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: 